spring.application.name=mundial
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.datasource.url=${PSQL_SIGNATURE:jdbc:postgresql://localhost:5432/quiniela}
spring.datasource.username=usrgerson
spring.datasource.password=12345

quiniela.jwt.secret=TuClaveSecretaSuperLargaYSeguraDeAlMenos256BitsParaElMundial2026!
quiniela.jwt.expiration=86400000

#SOLO DESARROLLO
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=default